name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        # Laravel 12 ต้องการ PHP 8.2+, รวม PHP 8.4 สำหรับการทดสอบ forward compatibility
        php: [8.4, 8.3, 8.2]
        laravel: [10.*, 11.*, 12.*]
        stability: [prefer-stable]
        include:
          # Laravel 10.x รองรับ PHP 8.1+ และใช้ TestBench 8.x
          - laravel: 10.*
            testbench: 8.*
          # Laravel 11.x ต้องการ PHP 8.2+ และใช้ TestBench 9.x
          - laravel: 11.*
            testbench: 9.*
          # Laravel 12.x ต้องการ PHP 8.2+ และใช้ TestBench 10.x
          - laravel: 12.*
            testbench: 10.*
        exclude:
          # Laravel 11.x และ 12.x ไม่รองรับ PHP 8.1
          - laravel: 11.*
            php: 8.1
          - laravel: 12.*
            php: 8.1
          # Laravel 10.x อาจไม่รองรับ PHP 8.4 อย่างสมบูรณ์
          - laravel: 10.*
            php: 8.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci

      # เพิ่ม step สำหรับ health check (Laravel 12 มี built-in health check)
      - name: Health Check (Laravel 12+)
        if: contains(matrix.laravel, '12.*')
        run: |
          php artisan serve --host=127.0.0.1 --port=8000 &
          sleep 2
          curl -f http://127.0.0.1:8000/up || exit 1
        continue-on-error: true
